version: "3.8"

services:
  db:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rag
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/rag
      NODE_ENV: development
      PORT: ${PORT:-57352}
    ports:
      - "${PORT:-57352}:${PORT:-57352}"
    volumes:
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
